import { useLocation } from 'react-router-dom'
import { useEffect, type ReactNode, useState } from 'react'
import { Bell, BookOpen, CalendarDays, Home, Moon, Settings, Sun } from 'lucide-react'
import { Link, NavLink } from 'react-router-dom'
import type { SessionState, ThemeMode } from '../lib/types'
import { useTheme } from '../lib/useTheme'
import { api, ApiError } from '../lib/api'
import { t, useLocale } from '../lib/i18n'
import { Button, Status } from '../design-system'

const nav = [{ to: '/', label: 'Today', icon: Home }, { to: '/problems', label: 'Problem library', icon: BookOpen }, { to: '/dashboard', label: 'Dashboard', icon: CalendarDays }, { to: '/notices', label: 'Notices', icon: Bell }]
export function AppShell({ children, session, sessionError }: { children: ReactNode; session: SessionState | null; sessionError?: boolean; onRefresh?: () => void }) {
  const location = useLocation(); const { mode, setMode } = useTheme(); const profile = session?.profile; const { locale } = useLocale(profile?.locale); const [unread, setUnread] = useState(0)
  useEffect(() => { if (!session?.authenticated) { setUnread(0); return }; api.notices(locale).then((value) => setUnread(value.unreadCount)).catch(() => undefined) }, [session?.authenticated, locale])
  const nextTheme: ThemeMode = mode === 'dark' ? 'light' : mode === 'light' ? 'system' : 'dark';
  const labels = { Today: t(locale, 'today'), 'Problem library': t(locale, 'library'), Dashboard: t(locale, 'dashboard'), Notices: t(locale, 'notices'), Settings: t(locale, 'settings') }
  return <div className="app-shell"><aside className="sidebar"><NavBrand /><div className="nav-section"><div className="nav-label">Practice</div>{nav.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} className="nav-item" aria-current={location.pathname === to ? 'page' : undefined}><Icon size={18} aria-hidden="true" /><span>{labels[label as keyof typeof labels] ?? label}</span>{label === 'Notices' && unread > 0 && <span className="unread-badge" aria-label={`${unread} unread`}>{unread > 99 ? '99+' : unread}</span>}</NavLink>)}</div><div className="nav-section"><div className="nav-label">Account</div><NavLink to="/settings" className="nav-item" aria-current={location.pathname === '/settings' ? 'page' : undefined}><Settings size={18} aria-hidden="true" /><span>{labels.Settings}</span></NavLink></div><div className="sidebar-bottom"><Button variant="subtle" icon={mode === 'dark' ? <Sun size={16} /> : <Moon size={16} />} onClick={() => setMode(nextTheme)}><span>{mode === 'system' ? 'System theme' : mode === 'dark' ? 'Dark theme' : 'Light theme'}</span></Button><div className="small muted" style={{ padding: '4px 10px' }}>Keyboard-first · offline-ready</div></div></aside><div className="main-area"><header className="topbar"><div className="topbar-title"><h1>SchemaSprint</h1><p>{pageLabel(location.pathname)}</p></div><div className="topbar-actions">{session?.authenticated ? <div className="avatar" aria-label={`Signed in as ${profile?.displayName ?? 'learner'}`}>{(profile?.displayName ?? 'L').slice(0, 1).toUpperCase()}</div> : <Link className="btn btn-subtle" to="/signin">{t(locale, 'signIn')}</Link>}</div></header>{sessionError && <div style={{ padding: '14px clamp(18px,3vw,42px) 0' }}><Status tone="danger" title="Service unavailable">The session could not be checked. No signed-out state was assumed; retry after reconnecting.</Status></div>}{session && !session.authenticated && !sessionError && <div style={{ padding: '14px clamp(18px,3vw,42px) 0' }}><Status tone="info" title="Preview mode">Sign in with Google or GitHub to submit, save server drafts, and track your practice.</Status></div>}{session?.authenticated && session.gates && (!session.gates.ageDeclared || !session.gates.policiesCurrent) && location.pathname !== '/onboarding' && <div style={{ padding: '14px clamp(18px,3vw,42px) 0' }}><Status tone="warning" title="Onboarding required"><Link to="/onboarding">{t(locale, 'onboarding')}</Link> before submitting or synchronizing drafts.</Status></div>}{children}</div><MobileNav locale={locale} unread={unread} /></div>
}
function NavBrand() { return <NavLink to="/" className="brand" aria-label="SchemaSprint home"><span className="brand-mark">S</span><span><span className="brand-wordmark">SchemaSprint</span><br /><span className="brand-sub">Design with intent</span></span></NavLink> }
function MobileNav({ locale, unread }: { locale: SessionState['profile'] extends never ? never : ReturnType<typeof useLocale>['locale']; unread: number }) { const location = useLocation(); return <nav className="mobile-nav" aria-label="Mobile navigation">{nav.slice(0, 4).map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} aria-current={location.pathname === to ? 'page' : undefined}><Icon size={20} aria-hidden="true" /><span>{t(locale, label === 'Today' ? 'today' : label === 'Problem library' ? 'library' : label === 'Dashboard' ? 'dashboard' : 'notices')}</span>{label === 'Notices' && unread > 0 && <span className="unread-badge">{unread}</span>}</NavLink>)}</nav> }
function pageLabel(path: string) { if (path.startsWith('/problem/')) return 'Workspace'; if (path === '/problems') return 'Problem library'; if (path === '/dashboard') return 'Your practice'; if (path === '/settings') return 'Account settings'; if (path === '/notices') return 'Updates and corrections'; return 'Daily practice'; }
export function SessionGate({ children, onSession }: { children: ReactNode; onSession: (session: SessionState | null) => void }) { const [session, setSession] = useState<SessionState | null>(null); useEffect(() => { api.session().then((value) => { setSession(value); onSession(value) }).catch((error: unknown) => { if (error instanceof ApiError && [401, 403].includes(error.status)) { const anonymous = { authenticated: false, csrfToken: null, gates: null } satisfies SessionState; setSession(anonymous); onSession(anonymous) } else { setSession(null); onSession(null) } }) }, [onSession]); return <AppShell session={session} onRefresh={() => undefined}>{children}</AppShell> }
