import { useEffect, useState } from 'react'
import { Bell, Check } from 'lucide-react'
import { api, ApiError } from '../lib/api'
import { useLocale } from '../lib/i18n'
import type { Notice, NoticePage, SessionState } from '../lib/types'
import { Button, EmptyState, ErrorState, LoadingState, SectionHeader, Status } from '../design-system'

export function NoticesPage({ session }: { session: SessionState | null }) { const { locale } = useLocale(session?.profile?.locale); const [data, setData] = useState<NoticePage | null>(null); const [error, setError] = useState(''); const [retry, setRetry] = useState(0); const [loadingMore, setLoadingMore] = useState(false)
  const load = (cursor?: string, append = false) => { if (!session?.authenticated) return; if (append) setLoadingMore(true); else setData(null); api.notices(locale, cursor).then((value) => { setData((current) => append && current ? { ...value, items: [...current.items, ...value.items] } : value); setError('') }).catch((e: unknown) => setError(e instanceof ApiError ? e.problem.detail ?? e.problem.title : e instanceof Error ? e.message : 'Unable to load notices.')).finally(() => setLoadingMore(false)) }
  useEffect(() => { load() }, [session?.authenticated, locale, retry]) // eslint-disable-line react-hooks/exhaustive-deps
  if (!session?.authenticated) return <main className="page"><Status tone="warning" title="Sign-in required">Updates and correction history are shown for registered learners.</Status></main>; if (error && !data) return <main className="page"><ErrorState message={error} onRetry={() => setRetry((value) => value + 1)} /></main>; if (!data) return <LoadingState label="Loading notices…" />; return <main className="page"><div className="page-header"><div><p className="eyebrow">Transparent updates</p><h2>Notices</h2><p>Approved corrections and product updates remain readable after publication.</p></div><div className="avatar"><Bell size={17} /></div></div>{error && <Status tone="danger">{error}</Status>}<section className="panel"><SectionHeader title={`${data.items.length} notices`} description={data.unreadCount ? `${data.unreadCount} unread` : 'You are all caught up.'} />{data.items.length ? data.items.map((notice) => <NoticeRow key={notice.versionId} notice={notice} csrf={session.csrfToken} onRead={() => setData((current) => current ? { ...current, unreadCount: Math.max(0, current.unreadCount - 1) } : current)} />) : <EmptyState title="No notices yet" message="Approved updates will appear here." />}{data.nextCursor && <div className="panel-pad"><Button variant="subtle" disabled={loadingMore} onClick={() => load(data.nextCursor ?? undefined, true)}>{loadingMore ? 'Loading…' : 'Load more'}</Button></div>}</section></main> }
function NoticeRow({ notice, csrf, onRead }: { notice: Notice; csrf: string | null; onRead: () => void }) { const [read, setRead] = useState(notice.read); const [error, setError] = useState(''); const mark = () => { if (!csrf || read) return; api.markNoticeRead(notice.versionId, csrf).then(() => { setRead(true); onRead() }).catch((e: unknown) => setError(e instanceof Error ? e.message : 'Could not mark as read.')) }; return <article className="panel-pad" style={{ borderBottom: '1px solid var(--color-border)' }}><div className="toolbar"><span className={`badge ${read ? '' : 'badge-mid'}`}>{read ? 'Read' : 'New'}</span><time className="small muted" dateTime={notice.publishedAt}>{new Date(notice.publishedAt).toLocaleDateString()}</time>{!read && <Button variant="subtle" icon={<Check size={14} />} onClick={mark}>Mark read</Button>}</div><h3 style={{ margin: '12px 0 6px' }}>{notice.title}</h3><p style={{ whiteSpace: 'pre-wrap', margin: 0 }}>{notice.body}</p>{error && <p className="field-error" role="alert">{error}</p>}</article> }
