import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { api, ApiError } from '../lib/api'
import type { Policy, SessionState } from '../lib/types'
import { Button, LoadingState, Status } from '../design-system'

export function OnboardingPage({ session, onComplete }: { session: SessionState | null; onComplete: () => void }) {
  const navigate = useNavigate(); const [policies, setPolicies] = useState<Policy[]>([]); const requiredPolicies = policies.filter((item) => !item.acknowledged); const [age, setAge] = useState(false); const [accepted, setAccepted] = useState<string[]>([]); const [name, setName] = useState(session?.profile?.displayName ?? ''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => { if (!session?.authenticated) return; api.policies().then((value) => setPolicies(value as Policy[])).catch((e: unknown) => setError(e instanceof Error ? e.message : 'Policies could not be loaded.')) }, [session?.authenticated])
  useEffect(() => { if (session?.gates?.ageDeclared && session.gates.policiesCurrent) navigate('/') }, [navigate, session?.gates?.ageDeclared, session?.gates?.policiesCurrent])
  if (session === null) return <LoadingState label="Checking session…" />
  if (!session.authenticated) return <main className="page"><Status tone="warning" title="Sign-in required">Sign in before completing onboarding.</Status></main>
  if (session.gates?.ageDeclared && session.gates.policiesCurrent) return <LoadingState label="Opening practice…" />
  const submit = () => { if (!session.csrfToken || !age || accepted.length !== requiredPolicies.length) return; setBusy(true); api.onboarding({ isAtLeast16: true, displayName: name.trim() || undefined, policyVersionIds: accepted }, session.csrfToken).then(() => { onComplete(); navigate('/') }).catch((e: unknown) => { setError(e instanceof ApiError ? e.problem.detail ?? e.problem.title : e instanceof Error ? e.message : 'Onboarding could not be completed.') }).finally(() => setBusy(false)) }
  return <main className="page onboarding-page"><div className="page-header"><div><p className="eyebrow">Account setup</p><h2>Complete the learning gates</h2><p>These checks are required before submitting or synchronizing learner data.</p></div></div>{error && <Status tone="danger" title="Could not continue">{error}</Status>}<section className="panel panel-pad stack"><div className="field"><label htmlFor="onboarding-name">Display name (optional)</label><input id="onboarding-name" className="input" maxLength={64} value={name} onChange={(event) => setName(event.target.value)} /></div><label className="check-row"><input type="checkbox" checked={age} onChange={(event) => setAge(event.target.checked)} /> I confirm that I am at least 16 years old.</label><div className="stack">{requiredPolicies.map((policy) => <label className="check-row" key={policy.id}><input type="checkbox" checked={accepted.includes(policy.id)} onChange={(event) => setAccepted((current) => event.target.checked ? [...current, policy.id] : current.filter((id) => id !== policy.id))} /> <span><strong>{policy.kind} · version {policy.version}</strong><br /><span className="small muted">{policy.content}</span></span></label>)}</div><Button variant="primary" disabled={busy || !age || accepted.length !== requiredPolicies.length} onClick={submit}>{busy ? 'Submitting…' : 'Complete onboarding'}</Button></section></main>
}
