import type { CanonicalSchema, Cardinality, EditorSources, InputFormat, SchemaColumn, SchemaRelationship, SchemaTable } from './types'

export type Diagnostic = { severity: 'error' | 'warning' | 'info'; message: string; line?: number }
const id = (prefix: string, value: string) => `${prefix}_${value.toLowerCase().replace(/[^a-z0-9_]+/g, '_') || crypto.randomUUID().slice(0, 8)}`
const blank = (): CanonicalSchema => ({ schemaVersion: 1, tables: [], relationships: [] })
function column(name: string, type: string, nullable = true, primaryKey = false): SchemaColumn { return { id: id('col', name), name, dataType: type, nullable, primaryKey } }
function table(name: string, columns: SchemaColumn[] = []): SchemaTable { return { id: id('tbl', name), name, columns, indexes: [], checks: [], position: { x: 60, y: 60 } } }

function splitDefinitions(body: string) { const parts: string[] = []; let start = 0; let depth = 0; for (let index = 0; index < body.length; index += 1) { const char = body[index]; if (char === '(') depth += 1; else if (char === ')') depth -= 1; else if (char === ',' && depth === 0) { parts.push(body.slice(start, index)); start = index + 1 } } parts.push(body.slice(start)); return parts }
function parseColumns(body: string) { return splitDefinitions(body).map((line) => line.trim()).filter(Boolean).map((line) => { if (/^(?:constraint|primary\s+key|foreign\s+key|unique|check)\b/i.test(line)) return null; const match = line.match(/^["`]?([\w-]+)["`]?\s+([\w().]+(?:\s+with\s+time\s+zone)?)(?:\s+(.*))?$/i); if (!match) return null; const [, name, type, flags = ''] = match; return column(name, type, !/not\s+null/i.test(flags), /primary\s+key/i.test(flags)) }).filter((item): item is SchemaColumn => item !== null) }
function relation(from: SchemaTable, fromColumns: string[], to: SchemaTable, toColumns: string[]): SchemaRelationship | null {
  const fromColumnIds = fromColumns.map((value) => from.columns.find((item) => item.name.toLowerCase() === value.trim().toLowerCase())?.id).filter((value): value is string => Boolean(value))
  const toColumnIds = toColumns.map((value) => to.columns.find((item) => item.name.toLowerCase() === value.trim().toLowerCase())?.id).filter((value): value is string => Boolean(value))
  if (!fromColumnIds.length || !toColumnIds.length) return null
  return { id: crypto.randomUUID(), fromTableId: from.id, fromColumnIds, toTableId: to.id, toColumnIds, fromCardinality: '0..*', toCardinality: '1', onDelete: 'no_action' }
}

function parseDdl(source: string): CanonicalSchema {
  const schema = blank(); const byName = new Map<string, SchemaTable>(); const bodies: { table: SchemaTable; body: string }[] = []
  const createPattern = /create\s+table\s+(?:if\s+not\s+exists\s+)?["`]?([\w-]+)["`]?(?:\s*\.\s*["`]?([\w-]+)["`]?)?\s*\(/gi
  for (const match of source.matchAll(createPattern)) { const start = (match.index ?? 0) + match[0].length; let depth = 1; let end = start; for (; end < source.length && depth > 0; end += 1) { if (source[end] === '(') depth += 1; else if (source[end] === ')') depth -= 1 } if (depth !== 0) continue; const body = source.slice(start, end - 1); const name = match[2] ?? match[1]; const current = table(name); current.columns = parseColumns(body); const pk = body.match(/primary\s+key\s*\(([^)]+)\)/i); if (pk) current.columns.forEach((item) => { if (pk[1].split(',').some((value) => value.trim().replace(/["`]/g, '').toLowerCase() === item.name.toLowerCase())) item.primaryKey = true }); byName.set(name.toLowerCase(), current); schema.tables.push(current); bodies.push({ table: current, body }) }
  for (const { table: fromTable, body } of bodies) {
    for (const match of body.matchAll(/foreign\s+key\s*\(([^)]+)\)\s*references\s+["`]?([\w-]+)["`]?\s*\(([^)]+)\)/gis)) { const target = byName.get(match[2].toLowerCase()); const item = target && relation(fromTable, match[1].split(','), target, match[3].split(',')); if (item) schema.relationships.push(item) }
    for (const match of body.matchAll(/["`]?([\w-]+)["`]?[\s\w(),]*?references\s+["`]?([\w-]+)["`]?\s*\(([^)]+)\)/gis)) { const target = byName.get(match[2].toLowerCase()); const item = target && relation(fromTable, [match[1]], target, match[3].split(',')); if (item && !schema.relationships.some((existing) => existing.fromTableId === item.fromTableId && existing.toTableId === item.toTableId && existing.fromColumnIds.join() === item.fromColumnIds.join())) schema.relationships.push(item) }
  }
  return schema
}
function parseDbml(source: string): CanonicalSchema {
  const schema = blank(); const byName = new Map<string, SchemaTable>()
  for (const match of source.matchAll(/table\s+([\w-]+)\s*\{([\s\S]*?)\}/gi)) { const current = table(match[1]); current.columns = match[2].split(/\r?\n/).map((line) => line.trim()).filter((line) => line && !/^(indexes|note)\b/i.test(line)).map((line) => { const item = line.match(/^["`]?([\w-]+)["`]?\s+([^\s[]+)(?:\s*\[([^\]]+)\])?/); if (!item) return null; return column(item[1], item[2], !/not\s+null/i.test(item[3] ?? ''), /\bpk\b|primary\s+key/i.test(item[3] ?? '')) }).filter((item): item is SchemaColumn => item !== null); byName.set(current.name.toLowerCase(), current); schema.tables.push(current) }
  for (const match of source.matchAll(/ref(?:erences)?\s*:\s*([\w-]+)\.([\w-]+)\s*([<>=-]+)\s*([\w-]+)\.([\w-]+)/gi)) { const from = byName.get(match[1].toLowerCase()); const to = byName.get(match[4].toLowerCase()); const item = from && to && relation(from, [match[2]], to, [match[5]]); if (item) { item.fromCardinality = match[3].includes('<') ? '0..*' : '1'; item.toCardinality = match[3].includes('>') ? '1' : '0..1'; schema.relationships.push(item) } }
  return schema
}
function parseMermaid(source: string): CanonicalSchema {
  const schema = blank(); const map = new Map<string, SchemaTable>();
  for (const match of source.matchAll(/^\s*([A-Za-z_][\w-]*)\s*\{([\s\S]*?)^\s*\}/gim)) { const current = table(match[1], match[2].split(/\r?\n/).map((line) => { const parts = line.trim().split(/\s+/); return parts.length >= 2 ? column(parts[1], parts[0], !/NOT\s+NULL/i.test(line), /\bPK\b/i.test(line)) : null }).filter((item): item is SchemaColumn => item !== null)); map.set(current.name.toLowerCase(), current); schema.tables.push(current) }
  const markerToCardinality = (marker: string): Cardinality => marker.includes('o') && marker.includes('{') ? '0..*' : marker.includes('|') && marker.includes('{') ? '1..*' : marker.includes('o') ? '0..1' : '1'
  for (const match of source.matchAll(/^\s*([A-Za-z_][\w-]*)\s+([|o.]{1,2}[{}]?)[-]+([|o.]{1,2}[{}]?)\s+([A-Za-z_][\w-]*)\s*:/gim)) { const from = map.get(match[1].toLowerCase()); const to = map.get(match[4].toLowerCase()); if (from && to) schema.relationships.push({ id: crypto.randomUUID(), fromTableId: from.id, fromColumnIds: [from.columns[0]?.id ?? ''], toTableId: to.id, toColumnIds: [to.columns[0]?.id ?? ''], fromCardinality: markerToCardinality(match[2]), toCardinality: markerToCardinality(match[3]), onDelete: 'no_action' }) }
  return schema
}
export function parseSource(format: EditorSources['activeFormat'], source: string): { schema?: CanonicalSchema; diagnostics: Diagnostic[] } {
  if (!source.trim()) return { schema: blank(), diagnostics: [{ severity: 'info', message: 'Start with a table definition or use the GUI.' }] }
  try { const schema = format === 'ddl' ? parseDdl(source) : format === 'dbml' ? parseDbml(source) : format === 'mermaid' ? parseMermaid(source) : blank(); const diagnostics = analyze(schema); if (!schema.tables.length) return { diagnostics: [{ severity: 'error', message: `Could not find a table in the ${format ?? 'source'} input. The last valid diagram remains visible.` }, ...diagnostics] }; return { schema, diagnostics } } catch { return { diagnostics: [{ severity: 'error', message: `Could not parse ${format ?? 'source'} input. The last valid diagram remains visible.` }] } }
}
export function analyze(schema: CanonicalSchema): Diagnostic[] {
  const diagnostics: Diagnostic[] = []; const names = new Set<string>(); const tableIds = new Set(schema.tables.map((item) => item.id));
  if (!schema.tables.length) diagnostics.push({ severity: 'warning', message: 'Add at least one table before submitting.' });
  for (const item of schema.tables) { if (names.has(item.name.toLowerCase())) diagnostics.push({ severity: 'error', message: `Duplicate table name: ${item.name}` }); names.add(item.name.toLowerCase()); const columns = new Set<string>(); if (!item.columns.length) diagnostics.push({ severity: 'warning', message: `${item.name} has no columns.` }); if (!item.columns.some((col) => col.primaryKey)) diagnostics.push({ severity: 'info', message: `${item.name} has no primary key; check the requirements.` }); for (const col of item.columns) { if (columns.has(col.name.toLowerCase())) diagnostics.push({ severity: 'error', message: `Duplicate column name in ${item.name}: ${col.name}` }); columns.add(col.name.toLowerCase()) } }
  for (const item of schema.relationships) { if (!tableIds.has(item.fromTableId) || !tableIds.has(item.toTableId)) diagnostics.push({ severity: 'error', message: `Relationship ${item.id} references a missing table.` }); if (!item.fromColumnIds.length || !item.toColumnIds.length) diagnostics.push({ severity: 'error', message: `Relationship ${item.id} must connect at least one column on each side.` }) }
  return diagnostics
}
export async function arrange(schema: CanonicalSchema): Promise<CanonicalSchema> {
  const { default: ELK } = await import('elkjs/lib/elk.bundled.js'); const elk = new ELK(); const result = await elk.layout({ id: 'schema', layoutOptions: { 'elk.algorithm': 'layered', 'elk.direction': 'RIGHT', 'elk.spacing.nodeNode': '80', 'elk.layered.spacing.nodeNodeBetweenLayers': '120' }, children: schema.tables.map((tableItem) => ({ id: tableItem.id, width: 220, height: Math.max(72, 44 + tableItem.columns.length * 26) })), edges: schema.relationships.map((relation) => ({ id: relation.id, sources: [relation.fromTableId], targets: [relation.toTableId] })) }); const positions = new Map((result.children ?? []).map((child) => [child.id, { x: child.x ?? 0, y: child.y ?? 0 }])); return { ...schema, tables: schema.tables.map((item) => ({ ...item, position: positions.get(item.id) ?? item.position })) }
}
export const initialSource = (schema: CanonicalSchema) => schema.tables.map((item) => `CREATE TABLE ${item.name} (\n${item.columns.map((col) => `  ${col.name} ${col.dataType}${col.primaryKey ? ' PRIMARY KEY' : ''}${col.nullable ? '' : ' NOT NULL'}`).join(',\n')}\n);`).join('\n\n')

export function serializeSource(format: InputFormat, schema: CanonicalSchema): string {
  if (format === 'ddl') return schema.tables.map((item) => { const foreignKeys = schema.relationships.filter((relationship) => relationship.fromTableId === item.id).map((relationship) => { const to = schema.tables.find((tableItem) => tableItem.id === relationship.toTableId); const fromNames = relationship.fromColumnIds.map((columnId) => item.columns.find((columnItem) => columnItem.id === columnId)?.name).filter((value): value is string => Boolean(value)); const toNames = relationship.toColumnIds.map((columnId) => to?.columns.find((columnItem) => columnItem.id === columnId)?.name).filter((value): value is string => Boolean(value)); return to && fromNames.length && toNames.length ? `  FOREIGN KEY (${fromNames.join(', ')}) REFERENCES ${to.name} (${toNames.join(', ')})` : '' }).filter(Boolean); return `CREATE TABLE ${item.name} (\n${[...item.columns.map((col) => `  ${col.name} ${col.dataType}${col.primaryKey ? ' PRIMARY KEY' : ''}${col.nullable ? '' : ' NOT NULL'}`), ...foreignKeys].join(',\n')}\n);` }).join('\n\n')
  if (format === 'dbml') return `${schema.tables.map((item) => `Table ${item.name} {\n${item.columns.map((col) => `  ${col.name} ${col.dataType}${col.primaryKey ? ' [pk]' : ''}${col.nullable ? '' : ' [not null]'}`).join('\n')}\n}`).join('\n\n')}${schema.relationships.map((item) => { const from = schema.tables.find((tableItem) => tableItem.id === item.fromTableId); const to = schema.tables.find((tableItem) => tableItem.id === item.toTableId); const fromColumn = from?.columns.find((columnItem) => columnItem.id === item.fromColumnIds[0]); const toColumn = to?.columns.find((columnItem) => columnItem.id === item.toColumnIds[0]); return from && to && fromColumn && toColumn ? `\n\nRef: ${from.name}.${fromColumn.name} > ${to.name}.${toColumn.name}` : '' }).join('')}`
  if (format === 'mermaid') { const marker = (cardinality: Cardinality) => cardinality === '0..*' ? 'o{' : cardinality === '1..*' ? '|{' : cardinality === '0..1' ? 'o|' : '||'; return `erDiagram\n${schema.tables.map((item) => `  ${item.name} {\n${item.columns.map((col) => `    ${col.dataType} ${col.name}${col.primaryKey ? ' PK' : ''}${col.nullable ? '' : ' NOT NULL'}`).join('\n')}\n  }`).join('\n')}${schema.relationships.map((item) => { const from = schema.tables.find((tableItem) => tableItem.id === item.fromTableId); const to = schema.tables.find((tableItem) => tableItem.id === item.toTableId); const fromColumn = from?.columns.find((columnItem) => columnItem.id === item.fromColumnIds[0]); const toColumn = to?.columns.find((columnItem) => columnItem.id === item.toColumnIds[0]); return from && to && fromColumn && toColumn ? `\n  ${from.name} ${marker(item.fromCardinality)}--${marker(item.toCardinality)} ${to.name} : "${fromColumn.name} to ${toColumn.name}"` : '' }).join('')}` }
  return ''
}
