export type Locale = 'en' | 'ja' | 'zh-CN' | 'ko' | 'es' | 'pt-BR'
export type Difficulty = 'easy' | 'mid' | 'hard'
export type InputFormat = 'gui' | 'mermaid' | 'ddl' | 'dbml' | 'mixed'
export type ThemeMode = 'system' | 'light' | 'dark'
export type Cardinality = '0..1' | '1' | '0..*' | '1..*'

export type SessionGates = { allowlisted: boolean; identityVerified: boolean; ageDeclared: boolean; policiesCurrent: boolean; mfaCurrent: boolean }
export type Entitlement = { premium: boolean; validUntil: string | null; billingEnabled: false; adsEnabled: false }
export type Profile = { id: string; displayName: string; locale: Locale; theme: ThemeMode; roles: string[]; entitlement: Entitlement }
export type SessionState = { authenticated: boolean; csrfToken: string | null; profile?: Profile | null; gates: SessionGates | null }
export type ProblemSummary = { id: string; version: number; title: string; difficulty: Difficulty; genre: string; inputFormat: InputFormat; tags: string[]; publicationDate: string; passed: boolean; submitted: boolean; translationStatus?: string }
export type SchemaColumn = { id: string; name: string; dataType: string; nullable: boolean; primaryKey?: boolean; defaultExpression?: string | null; generatedExpression?: string | null }
export type SchemaTable = { id: string; name: string; columns: SchemaColumn[]; indexes: Record<string, unknown>[]; checks: Record<string, unknown>[]; position: { x: number; y: number } }
export type SchemaRelationship = { id: string; fromTableId: string; fromColumnIds: string[]; toTableId: string; toColumnIds: string[]; fromCardinality: Cardinality; toCardinality: Cardinality; onDelete?: 'no_action' | 'restrict' | 'cascade' | 'set_null' | 'set_default' | null }
export type CanonicalSchema = { schemaVersion: 1; tables: SchemaTable[]; relationships: SchemaRelationship[]; enums?: Record<string, unknown>[]; views?: Record<string, unknown>[]; triggers?: Record<string, unknown>[]; policies?: Record<string, unknown>[]; partitions?: Record<string, unknown>[] }
export type EditorSources = { ddl?: string; mermaid?: string; dbml?: string; activeFormat?: InputFormat; warnings?: string[]; invalidFormats?: InputFormat[]; lastValidByFormat?: Partial<Record<'ddl' | 'mermaid' | 'dbml', CanonicalSchema>> }
export type ProblemDetail = ProblemSummary & { problemVersionId: string; statement: string; officialAnswer: CanonicalSchema; explanation: string; sourceLanguage: 'en'; requestedLocale: Locale; rubricSummary: { id: string; description: string; weight: number; critical: boolean; implicit: boolean }[] }
export type Draft = { problemId: string; revision: number; updatedAt: string; canonicalSchema: CanonicalSchema; editorSources: EditorSources; layout: Record<string, unknown> }
export type Submission = { id: string; problemId: string; problemVersionId: string; state: 'pending' | 'assessed' | 'failed'; canonicalSchema: CanonicalSchema; result: AssessmentResult | null; failureCode?: string | null; createdAt: string }
export type AssessmentResult = { score: number; exactFull: boolean; passed: boolean; contradiction: boolean; confidence: number; requirements: { rubricItemId: string; decision: 'satisfied' | 'not_met'; source: 'static' | 'jev'; confidence?: number | null; impact: string }[] }
export type Feedback = { id: string; version: number; content: string; contentEn: string; sourceLanguage: 'en'; translationStatus: string; modelVersion: string; createdAt: string }
export type Dashboard = { uniquePassed: number; byDifficulty: Record<string, number>; byWeekday: Record<string, number>; calendar: { publicationDate: string; passedProblemIds: string[] }[] }
export type CommunityPost = { id: string; submissionId: string; authorDisplayName: string; explanation: string; originalExplanation: string; sourceLanguage: string; schema: CanonicalSchema; moderationState: 'held' | 'approved' | 'rejected'; problemVersion: number; oldVersion?: boolean }
export type PostPage = { officialAnswer: CanonicalSchema; items: CommunityPost[]; nextCursor?: string | null }
export type Notice = { id: string; versionId: string; title: string; body: string; publishedAt: string; read: boolean }
export type NoticePage = { items: Notice[]; unreadCount: number; nextCursor?: string | null }
export type Job = { id: string; kind: string; state: 'pending' | 'leased' | 'succeeded' | 'failed'; retryAfterSeconds?: number; failureCode?: string | null }
export type ProblemError = { type: string; title: string; status: number; code: string; detail?: string; requestId?: string; retryable?: boolean; retryAfterSeconds?: number }
export type Policy = { id: string; kind: string; version: number; content: string; requiredFrom: string; acknowledged: boolean }
